version: '3.8'

services:
  gptsovits-service:
    build:
      context: ..
      dockerfile: mega-service-new/Dockerfile.gptsovits
      args:
        - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    container_name: projects-gptsovits-service
    working_dir: /app/service
    volumes:
      - ./app:/app/service
      - ./models:/app/models
      - ./audio:/app/audio
      - ./output:/app/output
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/service:/app/GPT_SoVITS:/app
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  tts-gptsovits:
    build:
      context: ..
      dockerfile: mega-service-new/Dockerfile.gptsovits
      args:
        - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    container_name: projects-tts-gptsovits
    working_dir: /app/service
    volumes:
      - ./app:/app/service
      - ./models:/app/models
      - ./audio:/app/audio
      - ./output:/app/output
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app/service:/app/GPT_SoVITS:/app
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped 